global:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-secret
          key: key
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-secret
          key: key
authentik:
  existingSecret:
    secretName: "authentik-secret"
    secretKey: "key"
server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    ingressClassName: nginx
    hosts:
      - auth.crust.life
postgresql:
  enabled: true
  persistence:
    storageClass: "harvester-longhorn"