authentik:
  existingSecret:
    secretName: "authentik-secret"
server:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-secret
          key: password
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    ingressClassName: nginx
    hosts:
      - auth.crust.life
worker:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-secret
          key: password
postgresql:
  enabled: true
  auth:
    existingSecret:
      secretName: "authentik-db-secret"
  persistence:
    storageClass: "harvester-longhorn"
redis:
  enabled: true
