global:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-secret
          key: password
authentik:
  existingSecret:
    secretName: "authentik-secret"
    secretKey: "secret_key"
server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    ingressClassName: "nginx"
    hosts:
      - auth.crust.life
postgresql:
  enabled: true
  auth:
    existingSecret: "authentik-db-secret"
  persistence:
    storageClass: "harvester-longhorn"
